import cv2
import numpy as np
import argparse
import os
import matplotlib.pyplot as plt

def extract_features_and_match(img1_path, img2_path):
    """
    Reads two images, detects SIFT features, computes descriptors, and matches them.
    Returns the keypoints, descriptors, and good matches.
    """
    img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

    if img1 is None or img2 is None:
        raise ValueError("Could not read one or both of the images.")

    # Initialize SIFT detector
    sift = cv2.SIFT_create()

    # Find keypoints and descriptors
    kp1, des1 = sift.detectAndCompute(img1, None)
    kp2, des2 = sift.detectAndCompute(img2, None)

    # Initialize BFMatcher with default params
    bf = cv2.BFMatcher()
    matches = bf.knnMatch(des1, des2, k=2)

    # Apply ratio test to find good matches
    good_matches = []
    pts1 = []
    pts2 = []
    for m, n in matches:
        if m.distance < 0.75 * n.distance:
            good_matches.append(m)
            pts1.append(kp1[m.queryIdx].pt)
            pts2.append(kp2[m.trainIdx].pt)

    pts1 = np.float32(pts1)
    pts2 = np.float32(pts2)

    return kp1, des1, kp2, des2, good_matches, pts1, pts2, img1, img2

def get_camera_intrinsics(image_shape):
    """
    Initializes the camera intrinsics matrix Ks per the assignment requirements.
    fx = fy = 0.7 * W
    cx = W / 2
    cy = H / 2
    """
    h, w = image_shape
    fx = 0.7 * w
    fy = 0.7 * w
    cx = w / 2.0
    cy = h / 2.0

    K = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1]
    ])
    return K

def enforce_rank2(E):
    """
    Enforces the rank-2 constraint on an Essential matrix using SVD.
    """
    U, S, Vt = np.linalg.svd(E)
    S_new = np.diag([S[0], S[1], 0]) # Set smallest singular value to 0
    E_rank2 = U @ S_new @ Vt
    return E_rank2

def estimate_essential_matrices(pts1, pts2, K):
    """
    Estimates E1 (using all correspondences, non-robust) and E2 (using RANSAC, robust).
    """
    # 1. Non-robust estimation (E1) using all points
    # We first find the Fundamental matrix F using the 8-point algorithm without RANSAC
    # cv2.FM_8POINT requires at least 8 matches and uses all provided points
    F1, _ = cv2.findFundamentalMat(pts1, pts2, cv2.FM_8POINT)
    
    # E = K.T * F * K
    if F1 is not None and F1.shape == (3, 3):
        E1_unconstrained = K.T @ F1 @ K
        E1 = enforce_rank2(E1_unconstrained)
    else:
        print("Warning: Could not compute valid F1. Falling back to identity or invalid matrix.")
        E1 = np.eye(3)

    # 2. Robust estimation (E2) using RANSAC
    # cv2.findEssentialMat directly calculates the Essential Matrix using robust methods
    E2, mask = cv2.findEssentialMat(pts1, pts2, K, method=cv2.RANSAC, prob=0.999, threshold=1.0)
    
    # Enforce rank-2 on E2 just to be safe, though OpenCV usually handles it for the primary solution
    # Note: cv2.findEssentialMat can return multiple 3x3 matrices stacked vertically (e.g. 9x3) if there are multiple solutions.
    # We just take the first one (top 3x3 block).
    if E2 is not None and E2.shape[0] >= 3:
        E2 = E2[:3, :]
        E2 = enforce_rank2(E2)
    else:
        print("Warning: Could not compute valid E2.")
        E2 = np.eye(3)

    return E1, E2, mask

def draw_epipolar_lines(img1, img2, pts1, pts2, F1, F2):
    """
    Draws epipolar lines in img2 corresponding to points in img1.
    Compares lines generated by F1 (from E1) and F2 (from E2).
    """
    # Select 10 random points
    np.random.seed(42) # For reproducibility
    indices = np.random.choice(len(pts1), min(10, len(pts1)), replace=False)
    
    rand_pts1 = pts1[indices]
    rand_pts2 = pts2[indices]
    
    # Compute epipolar lines in img2 for points in img1
    # cv2.computeCorrespondEpilines takes points in image 1, the image index (1 or 2), and the Fundamental matrix
    lines1 = cv2.computeCorrespondEpilines(rand_pts1.reshape(-1, 1, 2), 1, F1)
    lines1 = lines1.reshape(-1, 3)
    
    lines2 = cv2.computeCorrespondEpilines(rand_pts1.reshape(-1, 1, 2), 1, F2)
    lines2 = lines2.reshape(-1, 3)

    # Convert grayscale image to color for plotting colored lines/points
    img2_color = cv2.cvtColor(img2, cv2.COLOR_GRAY2BGR)
    
    h, w = img2.shape
    
    fig, axes = plt.subplots(1, 2, figsize=(15, 7))
    
    def draw_lines_on_image(img, lines, pts_img2, title):
        img_out = img.copy()
        for r, pt in zip(lines, pts_img2):
            color = tuple(np.random.randint(0, 255, 3).tolist())
            x0, y0 = map(int, [0, -r[2]/r[1] ])
            x1, y1 = map(int, [w, -(r[2]+r[0]*w)/r[1] ])
            img_out = cv2.line(img_out, (x0, y0), (x1, y1), color, 1)
            img_out = cv2.circle(img_out, tuple(map(int, pt)), 5, color, -1)
        return img_out

    img_lines1 = draw_lines_on_image(img2_color, lines1, rand_pts2, "Epipolar Lines (E1: All points)")
    img_lines2 = draw_lines_on_image(img2_color, lines2, rand_pts2, "Epipolar Lines (E2: RANSAC)")

    axes[0].imshow(cv2.cvtColor(img_lines1, cv2.COLOR_BGR2RGB))
    axes[0].set_title("Epipolar Lines (E1: All points)")
    axes[0].axis('off')

    axes[1].imshow(cv2.cvtColor(img_lines2, cv2.COLOR_BGR2RGB))
    axes[1].set_title("Epipolar Lines (E2: RANSAC)")
    axes[1].axis('off')

    plt.tight_layout()
    plt.savefig('epipolar_lines_comparison.png')
    print("Saved epipolar lines comparison to epipolar_lines_comparison.png")
    plt.show()

def main():
    parser = argparse.ArgumentParser(description="Task 1: Feature Correspondence and Essential Matrix Estimation")
    parser.add_argument("image1", help="Path to first image")
    parser.add_argument("image2", help="Path to second image")
    args = parser.parse_args()

    print(f"Loading images: {args.image1} and {args.image2}")
    
    # 1. Feature Detection and Matching
    kp1, des1, kp2, des2, good_matches, pts1, pts2, img1, img2 = extract_features_and_match(args.image1, args.image2)
    print(f"Found {len(good_matches)} good matches.")

    if len(good_matches) < 8:
        print("Error: Not enough good matches found (need at least 8).")
        return

    # 2. Essential Matrix Estimation
    K = get_camera_intrinsics(img1.shape)
    print(f"Camera Intrinsics Matrix K:\n{K}")

    E1, E2, mask = estimate_essential_matrices(pts1, pts2, K)
    
    print(f"\nEssential Matrix E1 (All correspondences):\n{E1}")
    print(f"\nEssential Matrix E2 (RANSAC):\n{E2}")

    # To draw epipolar lines, we need the Fundamental Matrices
    # F = (K^-T) * E * (K^-1)
    K_inv = np.linalg.inv(K)
    F1 = K_inv.T @ E1 @ K_inv
    F2 = K_inv.T @ E2 @ K_inv

    # 3. Visualize Epipolar Lines
    print("\nGenerating epipolar lines visualization...")
    draw_epipolar_lines(img1, img2, pts1, pts2, F1, F2)

if __name__ == "__main__":
    main()
